spring:
    cloud:
        config:
            server:
                git:
                  uri: https://github.com/wuhulala/rpc3-spring-cloud
                  search-paths: conf-repo
                  basedir: D:/spring-cloud/config/git

server:
    port: 8888

