server:
  port: 9411
zipkin:
  storage:
    type: mysql
    mysql:
      host: localhost
      username: root
      password: root
  collector:
    kafka:
      group-id: server1
      topic: zipkin
      streams: 4
      bootstrap-servers: localhost:9092
management:
  metrics:
    web:
      server:
        auto-time-requests: false
