spring:
  application:
    name: REGISTRY

server:
  port: 1003

eureka:
  instance:
    hostname: peer3
  client:
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://peer1:1001/eureka/
