server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  config: classpath:logback-spring.xml
spring:
  output:
    ansi:
      enabled: always

## 配置日志