spring:
  application:
    name: REGISTRY
server:
  port: 1001

eureka:
  instance:
    hostname: peer1
  client:
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://peer2:1002/eureka/